on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - feature*
      - bug*
  
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
         npm install
         npm test
     
