on:
  push:
    branches:
      - feature/128-github-actions
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Repository
        run: |
          git clone https://github.com/park-inn-ispp/park-inn-frontend.git
          cd park-inn-frontend
          git checkout develop
          "machine api.heroku.com/nlogin <your-email@address>/npassword/n<your-api-key>/nmachine git.heroku.com/nlogin/n<your-email@address>/npassword/n<your-api-key>" > ~/.netrc
          heroku login
  
