on:
  push:
    branches:
      - feature/128-github-actions
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Heroku Auth File
        run: |
          cd ~/
          > .netrc
          echo 'machine api.heroku.com' >> .netrc
          echo 'login ${{secrets.HEROKU_EMAIL}}' >> .netrc
          echo 'password ${{secrets.HEROKU_API_KEY}}' >> .netrc
          echo 'machine git.heroku.com' >> .netrc
          echo 'login ${{secrets.HEROKU_EMAIL}}' >> .netrc
          echo 'password ${{secrets.HEROKU_API_KEY}}' >> .netrc

      - name: Clone repository
        run: |
          git clone https://github.com/park-inn-ispp/park-inn-frontend.git
          cd park-inn-frontend
          git checkout develop
          heroku git:remote -a ${{secrets.HEROKU_APP_NAME}}
