on:
  push:
    branches:
      - feature/128-github-actions
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    
        
      - name: Deploy to heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:master -f
