on:
  push:
    branches:
      - feature/128-github-actions
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Repository
        run: |
          git clone https://github.com/park-inn-ispp/park-inn-frontend.git
          cd park-inn-frontend
          git checkout develop
          cd ~/
          > foo.bar
  
