on:
  push:
    branches:
      - feature/script_actions
jobs:
 Run-test-before-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Install SQL Server
      uses: Particular/install-sql-server-action@main
      with:
        connection-string-env-var: parkinn-dbsprint3.database.windows.net
    - name: Create schemas
      shell: pwsh
      run: |
          echo "Run tests"
          npm install
          npm test
